export const TRACK_SVGS = {
    bahrain: "https://upload.wikimedia.org/wikipedia/commons/d/db/2022_F1_CourseLayout_Bahrain.svg",
    jeddah: "https://upload.wikimedia.org/wikipedia/commons/3/38/2023_F1_CourseLayout_Saudi-Arabia.svg",
    albert_park: "https://upload.wikimedia.org/wikipedia/commons/c/cc/2023_F1_CourseLayout_Australia.svg",
    suzuka: "https://upload.wikimedia.org/wikipedia/commons/3/32/2022_F1_CourseLayout_Japan.svg",
    shanghai: "https://upload.wikimedia.org/wikipedia/commons/1/14/Shanghai_International_Racing_Circuit_track_map.svg",
    miami: "https://upload.wikimedia.org/wikipedia/commons/b/be/2022_F1_CourseLayout_Miami.svg",
    imola: "https://upload.wikimedia.org/wikipedia/commons/b/b9/2022_F1_CourseLayout_Imola.svg",
    monaco: "https://upload.wikimedia.org/wikipedia/commons/5/5e/2022_F1_CourseLayout_Monaco.svg",
    gilles_villeneuve: "https://upload.wikimedia.org/wikipedia/commons/4/45/2022_F1_CourseLayout_Canada.svg",
    villeneuve: "https://upload.wikimedia.org/wikipedia/commons/4/45/2022_F1_CourseLayout_Canada.svg",
    montmelo: "https://upload.wikimedia.org/wikipedia/commons/2/25/2023_F1_CourseLayout_Spain.svg",
    catalunya: "https://upload.wikimedia.org/wikipedia/commons/2/25/2023_F1_CourseLayout_Spain.svg",
    red_bull_ring: "https://upload.wikimedia.org/wikipedia/commons/0/09/2022_F1_CourseLayout_Austria.svg",
    silverstone: "https://upload.wikimedia.org/wikipedia/commons/4/46/2022_F1_CourseLayout_Britain.svg",
    hungaroring: "https://upload.wikimedia.org/wikipedia/commons/f/fb/2022_F1_CourseLayout_Hungary.svg",
    spa: "https://upload.wikimedia.org/wikipedia/commons/6/69/2022_F1_CourseLayout_Belgium.svg",
    zandvoort: "https://upload.wikimedia.org/wikipedia/commons/9/9f/2022_F1_CourseLayout_Netherlands.svg",
    monza: "https://upload.wikimedia.org/wikipedia/commons/6/68/2022_F1_CourseLayout_Italia.svg",
    baku: "https://upload.wikimedia.org/wikipedia/commons/a/af/2023_F1_CourseLayout_Azerbaijan.svg",
    marina_bay: "https://upload.wikimedia.org/wikipedia/commons/2/24/2022_F1_CourseLayout_Singapore.svg",
    austin: "https://upload.wikimedia.org/wikipedia/commons/b/b4/2022_F1_CourseLayout_COTA.svg",
    americas: "https://upload.wikimedia.org/wikipedia/commons/b/b4/2022_F1_CourseLayout_COTA.svg",
    hermanos_rodriguez: "https://upload.wikimedia.org/wikipedia/commons/2/2e/2022_F1_CourseLayout_Mexico.svg",
    rodriguez: "https://upload.wikimedia.org/wikipedia/commons/2/2e/2022_F1_CourseLayout_Mexico.svg",
    interlagos: "https://upload.wikimedia.org/wikipedia/commons/c/c6/2022_F1_CourseLayout_S%C3%A3o_Paulo.svg",
    vegas: "https://upload.wikimedia.org/wikipedia/commons/4/43/2023_Las_Vegas_street_circuit.svg",
    lusail: "https://upload.wikimedia.org/wikipedia/commons/b/bf/2023_F1_CourseLayout_Qatar.svg",
    yas_marina: "https://upload.wikimedia.org/wikipedia/commons/2/24/2022_F1_CourseLayout_Abu_Dhabi.svg",
    ricard: "https://upload.wikimedia.org/wikipedia/commons/0/00/2022_F1_CourseLayout_France.svg",
    istanbul: "https://upload.wikimedia.org/wikipedia/commons/7/78/Circuit_Istanbul.svg",
    sochi: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Circuit_Sochi.svg",
    portimao: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Aut%C3%B3dromo_do_Algarve_moto.svg",
    nurburgring: "https://upload.wikimedia.org/wikipedia/commons/7/76/N%C3%BCrburgring_-_Grand-Prix-Strecke.svg",
    mugello: "https://upload.wikimedia.org/wikipedia/commons/3/38/Mugello_Racing_Circuit_track_map_15_turns.svg",
    hockenheimring: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Circuit_Hockenheim_2002.svg",
    sepang: "https://upload.wikimedia.org/wikipedia/commons/7/72/Circuit_Sepang_1999.svg",
    buddh: "https://upload.wikimedia.org/wikipedia/commons/6/69/Buddh_Circuit.svg",
    yeongam: "https://upload.wikimedia.org/wikipedia/commons/9/91/Korea_international_circuit.svg",
    valencia: "https://upload.wikimedia.org/wikipedia/commons/d/db/Circuit_Valencia_2008.svg",
    fuji: "https://upload.wikimedia.org/wikipedia/commons/8/85/Circuit_Fuji.svg",
    magny_cours: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Circuit_de_Nevers_Magny-Cours_%281992-2002%29.svg",
    indianapolis: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Indianapolis_Motor_Speedway_-_road_course.svg",
    galvez: "https://upload.wikimedia.org/wikipedia/commons/9/95/Aut%C3%B3dromo_Oscar_Alfredo_G%C3%A1lvez_-_zoomed_in.svg",
    jerez: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Jerez_Grand_prix_Circuit_1994-2003.svg",
    estoril: "https://upload.wikimedia.org/wikipedia/commons/3/39/Estoril_track_map.svg",
};

export function getTrackImage(circuitId: string): string {
    return TRACK_SVGS[circuitId.toLowerCase() as keyof typeof TRACK_SVGS] || "https://upload.wikimedia.org/wikipedia/commons/3/33/F1.svg";
}